### PR TITLE
Implement FS orphan file cleanup

### PR DESCRIPTION
**Pull request by Vorlias**
Cleans out any files or folders that don't have a matching file/folder in `rootDir`. 

Basic working implementation, subject to change.

### CODE REVIEW

**Comment by Vorlias** [comment]
> 
> 
> Seems good. Have you considered doing it after compile instead of before?

Yeah, actually did think about that last night. Not quite sure at the moment if it makes a difference, but there's a possibility there for some future reason it will. 🤔

**Comment by Dionysusnu** [comment]
If there are any diagnostics, we don't emit. It seems wrong to remove files, but not add new ones. If we remove after compile, it will only remove if it compiled successfully

**Comment by Vorlias** [comment]
Good point.

**Comment by osyrisrblx** [comment]
This looks good to me. We'll need a public API for handling "this file/folder in src was added/removed/deleted" for watch mode.

**Comment by Vorlias** [comment]
> 
> 
> This looks good to me. We'll need a public API for handling "this file/folder in src was added/removed/deleted" for watch mode.

Yeah I'll probably look into that at some point if you don't. ;P

**Pull request merged**
